# Generated by Django 3.0.8 on 2020-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drumname', models.CharField(max_length=30, unique=True, verbose_name='药物名称')),
                ('description', models.CharField(max_length=120, verbose_name='药物性状')),
                ('indications', models.CharField(max_length=120, verbose_name='药物的适用症')),
                ('administration', models.CharField(max_length=120, verbose_name='剂量与用法')),
                ('note', models.CharField(max_length=120, verbose_name='注意事项')),
                ('sideeffects', models.CharField(max_length=120, verbose_name='副作用')),
                ('contraindications', models.CharField(max_length=120, verbose_name='禁忌症')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药物说明书',
                'db_table': 'medicine',
            },
        ),
    ]
