# Generated by Django 3.0.8 on 2020-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=60, verbose_name='openid')),
                ('patientname', models.CharField(max_length=30, verbose_name='患者名称')),
                ('gender', models.CharField(max_length=2, verbose_name='性别[0]男,[1]女')),
                ('age', models.CharField(max_length=3, verbose_name='年龄')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话')),
                ('pastmedicalhistory', models.CharField(max_length=120, verbose_name='既往病史')),
                ('allergy', models.CharField(max_length=60, verbose_name='过敏情况')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人信息',
                'db_table': 'patient',
                'unique_together': {('openid', 'patientname', 'gender', 'age', 'telephone', 'pastmedicalhistory', 'allergy')},
            },
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drumname', models.CharField(max_length=30, verbose_name='药物名称')),
                ('description', models.CharField(max_length=120, verbose_name='药物性状')),
                ('indications', models.CharField(max_length=120, verbose_name='药物的适用症')),
                ('administration', models.CharField(max_length=120, verbose_name='剂量与用法')),
                ('note', models.CharField(max_length=120, verbose_name='注意事项')),
                ('sideeffects', models.CharField(max_length=120, verbose_name='副作用')),
                ('contraindications', models.CharField(max_length=120, verbose_name='禁忌症')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药物说明书',
                'db_table': 'medicine',
                'unique_together': {('drumname', 'description', 'indications', 'administration', 'note', 'sideeffects', 'contraindications')},
            },
        ),
    ]
