# Generated by Django 3.0.8 on 2020-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=60, unique=True, verbose_name='openid')),
                ('patientname', models.CharField(max_length=30, verbose_name='患者名称')),
                ('gender', models.IntegerField(max_length=1, verbose_name='性别[0]男,[1]女')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('telephone', models.IntegerField(max_length=11, verbose_name='电话')),
                ('pastmedicalhistory', models.CharField(max_length=120, verbose_name='既往病史')),
                ('allergy', models.CharField(max_length=60, verbose_name='过敏情况')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人信息',
                'db_table': 'patientname',
            },
        ),
    ]
