# Generated by Django 3.0.8 on 2020-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=3, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性别[0]男,[1]女'),
        ),
    ]
