# Generated by Django 3.0.8 on 2020-08-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200808_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomname', models.CharField(max_length=30, verbose_name='症状名称')),
                ('summary', models.CharField(max_length=120, verbose_name='概述')),
                ('pathogeny', models.CharField(max_length=120, verbose_name='病因')),
                ('diagnosis', models.CharField(max_length=120, verbose_name='诊断')),
                ('clinical', models.CharField(max_length=120, verbose_name='临床表现')),
                ('symptom', models.CharField(max_length=120, verbose_name='症状')),
                ('therapeutic', models.CharField(max_length=120, verbose_name='治疗方法')),
                ('prevention', models.CharField(max_length=120, verbose_name='预防')),
                ('highriskgroup', models.CharField(max_length=120, verbose_name='高危人群')),
                ('relateddiseases', models.CharField(max_length=120, verbose_name='相关疾病')),
            ],
            options={
                'verbose_name': '症状',
                'verbose_name_plural': '症状表现',
                'db_table': 'symptom',
                'unique_together': {('symptomname', 'summary', 'pathogeny', 'diagnosis', 'clinical', 'symptom', 'therapeutic', 'prevention', 'highriskgroup', 'relateddiseases')},
            },
        ),
    ]
