# Generated by Django 3.0.8 on 2020-08-03 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200803_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上次时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='patient',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上次时间'),
            preserve_default=False,
        ),
    ]
