# Generated by Django 3.0.8 on 2020-08-08 11:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=30, verbose_name='被回复者的用户名'),
        ),
        migrations.CreateModel(
            name='medicinewiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类名')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='api.medicine')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.medicinewiki')),
            ],
            options={
                'verbose_name': '药物wiki',
                'verbose_name_plural': '药物wiki信息',
                'db_table': 'medicinewiki',
            },
        ),
    ]
