# Generated by Django 3.0.8 on 2020-08-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200808_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirypost',
            name='summary',
            field=models.CharField(default=0, max_length=120, verbose_name='概述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
