# Generated by Django 3.0.8 on 2020-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200803_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性别[0]男,[1]女'),
        ),
    ]
