# Generated by Django 3.0.8 on 2020-08-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200803_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='uptime',
        ),
    ]
