# Generated by Django 3.0.8 on 2020-08-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200809_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicinewiki',
            new_name='symptomwiki',
        ),
        migrations.AlterModelOptions(
            name='symptomwiki',
            options={'verbose_name': '疾病wiki', 'verbose_name_plural': '疾病wiki信息'},
        ),
        migrations.AlterModelTable(
            name='symptomwiki',
            table='symptomwiki',
        ),
    ]
