# Generated by Django 3.0.8 on 2020-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200809_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirypost',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
