# Generated by Django 3.0.8 on 2020-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200809_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgmd5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picture/%Y%m%d/')),
                ('md5', models.CharField(max_length=60)),
            ],
        ),
    ]
