# Generated by Django 3.0.8 on 2020-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200803_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='openid',
            field=models.CharField(max_length=60, unique=True, verbose_name='openid'),
        ),
    ]
