# Generated by Django 3.0.8 on 2020-08-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imgmd5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirypost',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='inquirypost',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='inquirypost',
            name='picture3',
        ),
        migrations.AlterField(
            model_name='symptomwiki',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='api.symptom'),
        ),
    ]
