# Generated by Django 3.0.8 on 2020-08-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200803_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='drumname',
            field=models.CharField(max_length=30, verbose_name='药物名称'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('drumname', 'description', 'indications', 'administration', 'note', 'sideeffects', 'contraindications')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('openid', 'patientname', 'gender', 'age', 'telephone', 'pastmedicalhistory', 'allergy')},
        ),
    ]
