# Generated by Django 3.0.8 on 2020-08-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200811_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='administration',
            field=models.TextField(verbose_name='剂量与用法'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(verbose_name='禁忌症'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(verbose_name='药物性状'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drumname',
            field=models.TextField(verbose_name='药物名称'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=models.TextField(verbose_name='药物的适用症'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='note',
            field=models.TextField(verbose_name='注意事项'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sideeffects',
            field=models.TextField(verbose_name='副作用'),
        ),
    ]
