# Generated by Django 3.0.8 on 2020-08-11 03:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200811_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='clinical',
            field=ckeditor.fields.RichTextField(verbose_name='临床表现'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='diagnosis',
            field=ckeditor.fields.RichTextField(verbose_name='诊断'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='highriskgroup',
            field=ckeditor.fields.RichTextField(verbose_name='高危人群'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='pathogeny',
            field=ckeditor.fields.RichTextField(verbose_name='病因'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='prevention',
            field=ckeditor.fields.RichTextField(verbose_name='预防'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='relateddiseases',
            field=ckeditor.fields.RichTextField(verbose_name='相关疾病'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='summary',
            field=ckeditor.fields.RichTextField(verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=ckeditor.fields.RichTextField(verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='therapeutic',
            field=ckeditor.fields.RichTextField(verbose_name='治疗方法'),
        ),
    ]
