# Generated by Django 3.0.8 on 2020-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200811_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photourl',
            field=models.CharField(default=0, max_length=120, verbose_name='photourl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquirypost',
            name='photourl',
            field=models.CharField(default=0, max_length=120, verbose_name='photourl'),
            preserve_default=False,
        ),
    ]
