# Generated by Django 3.0.8 on 2020-08-12 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200811_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('img_url', models.CharField(max_length=120, verbose_name='预览图url')),
                ('text', ckeditor.fields.RichTextField(help_text='图片请使用sm.ms图床上传！！！', verbose_name='正文内容')),
                ('readnum', models.PositiveIntegerField(blank=True, default=0)),
                ('postwiki', models.ImageField(choices=[(0, '百科'), (1, '疫情'), (2, '药品')], upload_to='', verbose_name='分类')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯信息',
                'db_table': 'notify',
            },
        ),
    ]
