# Generated by Django 3.0.8 on 2020-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='postwiki',
            field=models.ImageField(choices=[(1, '百科'), (2, '疫情'), (3, '药品')], upload_to='', verbose_name='分类'),
        ),
    ]
