# Generated by Django 3.0.8 on 2020-08-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200812_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='level',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='tree_id',
        ),
    ]
