# Generated by Django 3.0.8 on 2020-08-13 18:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200812_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='administration',
            field=ckeditor.fields.RichTextField(verbose_name='剂量与用法'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=ckeditor.fields.RichTextField(verbose_name='禁忌症'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='药物性状'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drumname',
            field=ckeditor.fields.RichTextField(verbose_name='药物名称'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=ckeditor.fields.RichTextField(verbose_name='药物的适用症'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='note',
            field=ckeditor.fields.RichTextField(verbose_name='注意事项'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sideeffects',
            field=ckeditor.fields.RichTextField(verbose_name='副作用'),
        ),
    ]
