# Generated by Django 3.0.8 on 2020-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200813_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='postwiki',
            field=models.IntegerField(choices=[(1, '百科'), (2, '疫情'), (3, '药品')], verbose_name='分类'),
        ),
    ]
