# Generated by Django 3.0.8 on 2020-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200813_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='drumname',
            field=models.TextField(verbose_name='药物名称'),
        ),
    ]
