# Generated by Django 3.0.8 on 2020-08-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
